spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patternpatients
    username: postgres
    password: jemimanda
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html